import express from "express";
import Payslip from "../models/Payslip.js";
import PayslipBankHistory from "../models/PayslipBankHistory.js";
import User from "../models/User.js";
import { authMiddleware, requireRole } from "../middleware/auth.js";
import puppeteer from "puppeteer";

const router = express.Router();

/**
 * MANAGER – CREATE / UPDATE PAYSLIP
 */
router.post(
  "/",
  authMiddleware,
  requireRole(["manager"]),
  async (req, res) => {
    try {
      const {
        employeeId,
        employeeType,
        designation,
        month,
        year,
        templateId,
        bankDetails,
        salary
      } = req.body;

      const employee = await User.findById(employeeId);
      if (!employee)
        return res.status(404).json({ message: "Employee not found" });

      // save old bank details in history
      await PayslipBankHistory.create({
        employee: employeeId,
        ...bankDetails,
        changedBy: req.user.id
      });

      const payslip = await Payslip.findOneAndUpdate(
        { employee: employeeId, month, year },
        {
          employee: employeeId,
          employeeType,
          designation,
          month,
          year,
          templateId,
          bankDetails,
          salary,
          createdBy: req.user.id
        },
        { upsert: true, new: true }
      );

      res.status(201).json(payslip);
    } catch (err) {
      console.error("Create payslip error:", err);
      res.status(500).json({ message: err.message });
    }
  }
);

/**
 * MANAGER / ADMIN – LIST ALL PAYSLIPS
 */
router.get(
  "/all",
  authMiddleware,
  requireRole(["manager", "admin"]),
  async (req, res) => {
    const payslips = await Payslip.find()
      .populate("employee", "fullName email")
      .sort({ year: -1, month: -1 });

    res.json(payslips);
  }
);

/**
 * EMPLOYEE – MY PAYSLIPS
 */
router.get(
  "/my",
  authMiddleware,
  async (req, res) => {
    const payslips = await Payslip.find({ employee: req.user.id })
      .sort({ year: -1, month: -1 });

    res.json(payslips);
  }
);

/**
 * DOWNLOAD PDF (ALL ROLES WITH ACCESS)
 */
router.get(
  "/:id/download",
  authMiddleware,
  async (req, res) => {
    const payslip = await Payslip.findById(req.params.id)
      .populate("employee", "fullName email");

    if (!payslip)
      return res.status(404).json({ message: "Payslip not found" });

    // permission
    if (
      req.user.role === "employee" &&
      String(payslip.employee._id) !== req.user.id
    ) {
      return res.status(403).json({ message: "Forbidden" });
    }

    const html = `
      <html>
        <body>
          <h2 style="text-align:center">Company Name Pvt Ltd</h2>
          <p style="text-align:center">Company Address Line</p>
          <hr/>

          <p><strong>Employee:</strong> ${payslip.employee.fullName}</p>
          <p><strong>Email:</strong> ${payslip.employee.email}</p>
          <p><strong>Month:</strong> ${payslip.month}/${payslip.year}</p>

          <table width="100%" border="1" cellspacing="0" cellpadding="8">
            <tr><th>Earnings</th><th>Amount</th><th>Deductions</th><th>Amount</th></tr>
            <tr>
              <td>Basic</td><td>${payslip.salary.basic}</td>
              <td>PF</td><td>${payslip.salary.pf}</td>
            </tr>
            <tr>
              <td>HRA</td><td>${payslip.salary.hra}</td>
              <td>ESI</td><td>${payslip.salary.esi}</td>
            </tr>
            <tr>
              <td>Allowances</td><td>${payslip.salary.allowances}</td>
              <td>TDS</td><td>${payslip.salary.tds}</td>
            </tr>
            <tr>
              <td><strong>Gross</strong></td>
              <td><strong>${payslip.salary.grossEarnings}</strong></td>
              <td><strong>Net Pay</strong></td>
              <td><strong>${payslip.salary.netPay}</strong></td>
            </tr>
          </table>

          <p style="margin-top:20px;text-align:right">
            Generated by Attendance System
          </p>
        </body>
      </html>
    `;

    const browser = await puppeteer.launch({
      args: ["--no-sandbox", "--disable-setuid-sandbox"]
    });
    const page = await browser.newPage();
    await page.setContent(html);
    const pdf = await page.pdf({ format: "A4" });
    await browser.close();

    res.set({
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="payslip-${payslip.month}-${payslip.year}.pdf"`
    });

    res.send(pdf);
  }
);

export default router;
