// routes/payslipRoutes.js
import express from "express";
import { authMiddleware, requireRole } from "../middleware/auth.js";
import User from "../models/User.js";
import Attendance from "../models/Attendance.js";
import puppeteer from "puppeteer"; // npm i puppeteer
import path from "path";

const router = express.Router();

// simple HTML builder - replace with EJS/Handlebars in production
const buildHtml = (employee, month, year, fields, template) => {
  return `
    <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; color: #222; padding: 20px; }
          .header { display:flex; justify-content:space-between; align-items:center }
          table { width:100%; border-collapse:collapse; margin-top:10px }
          th, td { padding:8px; border-bottom:1px solid #eee; }
        </style>
      </head>
      <body>
        <div class="header">
          <div><h2>${template.header || "Company Name"}</h2></div>
          <div><strong>Payslip</strong><div>${month}/${year}</div></div>
        </div>

        <div><strong>Employee:</strong> ${employee.fullName} (${employee.email})</div>

        <table>
          <tr><th>Earnings</th><th style="text-align:right">Amount</th><th>Deductions</th><th style="text-align:right">Amount</th></tr>
          <tr><td>Basic</td><td style="text-align:right">${fields.basic}</td><td>Deductions</td><td style="text-align:right">${fields.deductions}</td></tr>
          <tr><td>HRA</td><td style="text-align:right">${fields.hra}</td><td></td><td></td></tr>
          <tr><td>Allowances</td><td style="text-align:right">${fields.allowances}</td><td></td><td></td></tr>
          <tfoot><tr><td><strong>Gross</strong></td><td style="text-align:right"><strong>${fields.basic + fields.hra + fields.allowances}</strong></td><td><strong>Net</strong></td><td style="text-align:right"><strong>${fields.basic + fields.hra + fields.allowances - fields.deductions}</strong></td></tr></tfoot>
        </table>

        <div style="margin-top:12px"><strong>Working days:</strong> ${fields.workingDays}</div>
        <div style="margin-top:12px"><strong>Notes:</strong> ${fields.notes || "-"}</div>

        <div style="margin-top:24px; text-align:right">${template.footer || ""}</div>
      </body>
    </html>
  `;
};

router.post(
  "/generate",
  authMiddleware,
  requireRole(["manager", "admin"]),
  async (req, res) => {
    try {
      const { employeeId, month, year, templateId, fields } = req.body;

      const employee = await User.findById(employeeId).lean();
      if (!employee) return res.status(404).json({ message: "Employee not found" });

      // Optional: compute workingDays server-side by reading Attendance documents (recommended)
      // const attendance = await Attendance.find({ user: employeeId, date: { $regex: `-${Number(month)}-${year}$` } });
      // compute from attendance if you want authoritative value.

      // select template by ID (you can store templates in DB)
      const template = {
        basic: { header: "Company Name Pvt Ltd", footer: "Generated by Attendance System" },
        compact: { header: "Company Name", footer: "" },
      }[templateId] || { header: "Company", footer: "" };

      // build HTML and convert to PDF with puppeteer
      const html = buildHtml(employee, month, year, fields || {}, template);

      const browser = await puppeteer.launch({ args: ["--no-sandbox", "--disable-setuid-sandbox"] });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0" });
      const pdfBuffer = await page.pdf({ format: "A4", printBackground: true });
      await browser.close();

      res.set({
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="payslip-${employee.fullName}-${month}-${year}.pdf"`
      });

      return res.send(pdfBuffer);
    } catch (err) {
      console.error("Payslip generation error:", err);
      return res.status(500).json({ message: err.message || "Error generating payslip" });
    }
  }
);

export default router;
